### ISSUE TITLE
Check dplasma ctest pass

### ISSUE THREAD

**Issue by abouteiller** [ICLDisco/parsec#619]
## Description
In preparation for v4.0, we use dplasma to validate correctness. This issue will track what does and does not work in dplasma. 

### Describe the solution you'd like
All parsec and dplasma ctest pass

### Describe alternatives you've considered
the *lowmem* dplasma testers don't pass and we may defer fixing this defect to v4.1 in the benefit of time.

## Additional context

* [ ] dplasma_xpotrf_dtd_xxx on GPU broken https://github.com/ICLDisco/dplasma/issues/113
* [ ] dplasma_xgemm_dtd_mpi on GPU broken https://github.com/ICLDisco/dplasma/issues/113
* [x] dplasma_spotrf_1gpu_lowmem_shm broken: resolved with #733 
* [ ] dplasma_sgemm_2gpu_lowmem_mpi broken #741 
* [x] geqrf/ormqr cause signal 8 (FP exception) This is a bug in dplasma https://github.com/ICLDisco/dplasma/issues/110

**Comment by abouteiller** [comment]
moved to 4.1, the remaining bugs that are not in dplasma itself are not understood and rare.

**Comment by abouteiller** [comment]
The other problems are still existing
