### ISSUE TITLE
Release prep: v4.0 supports TTG and Hicma

### ISSUE THREAD

**Issue by abouteiller** [ICLDisco/parsec#638]
## Task

* [x] TTG works on v4.0 (without GPU)
* [x] TTG works on v4.0 (with GPU)
* [x] Hicma works on v4.0 (without GPU)
* [x] Hicma works on v4.0 (with GPU)

**Comment by abouteiller** [comment]
@QingleiCao @devreal please report findings by clicking the box

**Comment by abouteiller** [comment]
@QingleiCao let me know if Hicma works on current master, I know you did run some tests yesterday

**Comment by QingleiCao** [comment]
Sure. what I'm using the the commit from March 6. I will have a try with the latest master next week.
